#!/bin/bash

sudo cp -r pack/pacman.conf /etc/
sudo pacman -Syy
sudo pacman -S --noconfirm mesa lib32-mesa -y
sudo pacman -S --noconfirm libva-mesa-driver mesa-vdpau opencl-mesa vulkan-mesa-layers mesa-demos vulkan-tools vulkan-intel -y
sudo pacman -S --noconfirm lib32-libva-mesa-driver lib32-mesa-vdpau lib32-opencl-mesa lib32-vulkan-intel lib32-vulkan-mesa-layers lib32-mesa-demos -y
sudo cp -r pack/modpac/pacman.conf /etc/
sudo pacman -Syy --noconfirm holoiso-stable/vulkan-intel

